"""S3/boto3 client construction shared by storage and preflight.

CSC ``allas-conf`` writes credentials to ``~/.aws/credentials`` and the Allas
endpoint to ``~/.aws/config``.  We deliberately rely on boto3's normal shared
configuration/credential chain rather than adding access keys or passwords to
LaclauGPT configuration.
"""
from __future__ import annotations

from dataclasses import dataclass
from urllib.parse import urlparse

ALLAS_HOSTS = frozenset({"a3s.fi"})
ADDRESSING_STYLES = frozenset({"auto", "path", "virtual"})
SIGNATURE_VERSIONS = frozenset({"auto", "s3", "s3v2", "v2", "s3v4", "v4"})


@dataclass(frozen=True, slots=True)
class S3ClientSpec:
    endpoint_url: str | None
    region: str | None
    addressing_style: str
    signature_version: str | None
    provider: str


def _clean(value: str | None) -> str | None:
    if value is None:
        return None
    stripped = value.strip()
    return stripped or None


def normalize_addressing_style(value: str | None) -> str:
    normalized = (_clean(value) or "auto").casefold()
    if normalized not in ADDRESSING_STYLES:
        allowed = ", ".join(sorted(ADDRESSING_STYLES))
        raise ValueError(f"unsupported S3 addressing style {value!r}; expected one of: {allowed}")
    return normalized


def normalize_signature_version(value: str | None) -> str | None:
    normalized = (_clean(value) or "auto").casefold()
    if normalized not in SIGNATURE_VERSIONS:
        allowed = ", ".join(sorted(SIGNATURE_VERSIONS))
        raise ValueError(f"unsupported S3 signature version {value!r}; expected one of: {allowed}")
    if normalized == "auto":
        return None
    if normalized in {"s3", "s3v2", "v2"}:
        # botocore calls AWS Signature Version 2 for S3 simply ``s3``.
        return "s3"
    return "s3v4"


def _shared_config_endpoint(session: object) -> str | None:
    """Read endpoint_url from boto3's active AWS profile without reading secrets."""
    botocore_session = getattr(session, "_session", None)
    if botocore_session is None:
        return None
    try:
        scoped = botocore_session.get_scoped_config()
    except (AttributeError, KeyError, TypeError, ValueError):
        return None
    if not isinstance(scoped, dict):
        return None
    return _clean(scoped.get("endpoint_url"))


def _is_allas(endpoint_url: str | None) -> bool:
    if not endpoint_url:
        return False
    candidate = endpoint_url if "://" in endpoint_url else f"https://{endpoint_url}"
    return (urlparse(candidate).hostname or "").casefold() in ALLAS_HOSTS


def build_s3_client(
    *,
    endpoint_url: str | None = None,
    region: str | None = None,
    addressing_style: str | None = "auto",
    signature_version: str | None = "auto",
):
    """Build boto3 S3 client using shared AWS config/credentials and safe overrides.

    When ``allas-conf`` is in use, no explicit endpoint, access key, secret key or
    password is required here: boto3 reads the generated ``~/.aws`` files.  If the
    resolved endpoint is CSC Allas, virtual-hosted addressing and S3 Signature V2
    are selected automatically because those are the settings generated by CSC for
    S3 clients.  Explicit LaclauGPT settings still override the auto behaviour.
    """
    try:
        import boto3
        from botocore.config import Config
    except ImportError as exc:  # pragma: no cover - optional dependency
        raise RuntimeError("S3 support requires: pip install '.[remote]'") from exc

    session = boto3.Session()
    resolved_endpoint = _clean(endpoint_url) or _shared_config_endpoint(session)
    resolved_region = _clean(region)
    resolved_addressing = normalize_addressing_style(addressing_style)
    resolved_signature = normalize_signature_version(signature_version)
    provider = "allas" if _is_allas(resolved_endpoint) else "s3"

    if provider == "allas":
        if resolved_addressing == "auto":
            resolved_addressing = "virtual"
        if resolved_signature is None:
            resolved_signature = "s3"

    config_kwargs: dict[str, object] = {}
    if resolved_addressing != "auto":
        config_kwargs["s3"] = {"addressing_style": resolved_addressing}
    if resolved_signature is not None:
        config_kwargs["signature_version"] = resolved_signature
    config = Config(**config_kwargs) if config_kwargs else None

    client = session.client(
        "s3",
        endpoint_url=resolved_endpoint,
        region_name=resolved_region,
        config=config,
    )
    spec = S3ClientSpec(
        endpoint_url=resolved_endpoint,
        region=resolved_region,
        addressing_style=resolved_addressing,
        signature_version=resolved_signature,
        provider=provider,
    )
    return client, spec
