"""AI26 RSS source metadata for the minimal Phase 0 corpus.

One corpus, many metadata views. Arenas and formations are filters/hints only.
Phase 0 collects RSS/Atom only, while actor_name is the canonical cross-platform
identity for later X/YouTube/etc. adapters.
"""

AI_FORMATIONS = {
    "existential_risk",
    "accelerationist",
    "left_accelerationist",
    "ai_safety",
    "critical_ai",
    "anti_ai",
    "other",
    "unknown",
}

POLITICAL_FORMATIONS = {
    "far_left",
    "centre_left",
    "centre",
    "centre_right",
    "far_right",
    "unknown",
}

ARENAS = {"elite", "parliamentary", "grassroots", "media", "science", "corporation", "other"}

ACTOR_TYPES = {
    "individual",
    "ai_system",
    "corporation",
    "party",
    "government",
    "parliament",
    "media",
    "movement",
    "institute",
    "publication",
    "other",
}

# Keep the seed list intentionally small and editable. Add only feeds that are
# known/stable enough to be useful for the first Phase 0 corpus.
SOURCES = [
    {
        "id": "lesswrong",
        "project": "ai26",
        "arena": "elite",
        "actor_name": "LessWrong",
        "actor_type": "publication",
        "ai_formation": "existential_risk",
        "political_formation": "unknown",
        "source_type": "rss",
        "source_name": "LessWrong RSS",
        "source_url": "https://www.lesswrong.com/",
        "feed_url": "https://www.lesswrong.com/feed.xml",
        "country": "US",
        "language": "en",
        "description": "Seed publication for AI existential-risk discourse.",
        "notes": "Preserve post authors; non-public users should be anonymized in published outputs.",
        "homepage_url": "https://www.lesswrong.com/",
        "active": True,
    },
    {
        "id": "nick_srnicek",
        "project": "ai26",
        "arena": "elite",
        "actor_name": "Nick Srnicek",
        "actor_type": "individual",
        "ai_formation": "left_accelerationist",
        "political_formation": "unknown",
        "source_type": "rss",
        "source_name": "Silicon Empires",
        "source_url": "https://siliconempires.substack.com/",
        "feed_url": "https://siliconempires.substack.com/feed",
        "country": "GB",
        "language": "en",
        "description": "Seed actor for left-accelerationist and post-work technological discourse.",
        "notes": "",
        "homepage_url": "https://siliconempires.substack.com/",
        "active": True,
    },
    {
        "id": "pauseai",
        "project": "ai26",
        "arena": "grassroots",
        "actor_name": "PauseAI",
        "actor_type": "movement",
        "ai_formation": "anti_ai",
        "political_formation": "unknown",
        "source_type": "rss",
        "source_name": "PauseAI RSS",
        "source_url": "https://pauseai.info/",
        "feed_url": "https://pauseai.substack.com/feed",
        "country": "NL",
        "language": "en",
        "description": "Seed grassroots pause/anti-AI movement.",
        "notes": "",
        "homepage_url": "https://pauseai.info/",
        "active": True,
    },
    {
        "id": "openai",
        "project": "ai26",
        "arena": "corporation",
        "actor_name": "OpenAI",
        "actor_type": "corporation",
        "ai_formation": "unknown",
        "political_formation": "unknown",
        "source_type": "rss",
        "source_name": "OpenAI News RSS",
        "source_url": "https://openai.com/news/",
        "feed_url": "https://openai.com/news/rss.xml",
        "country": "US",
        "language": "en",
        "description": "Major AI corporation.",
        "notes": "",
        "homepage_url": "https://openai.com/",
        "active": True,
    },
    {
        "id": "arxiv_ai_society",
        "project": "ai26",
        "arena": "science",
        "actor_name": "arXiv",
        "actor_type": "publication",
        "ai_formation": "unknown",
        "political_formation": "unknown",
        "source_type": "rss",
        "source_name": "arXiv cs.CY RSS",
        "source_url": "https://arxiv.org/list/cs.CY/recent",
        "feed_url": "https://rss.arxiv.org/rss/cs.CY",
        "country": "US",
        "language": "en",
        "description": "Scientific and societal computing research, including AI governance and social implications.",
        "notes": "Authors are preserved per item; individual scholars are not automatically promoted to canonical actors.",
        "homepage_url": "https://arxiv.org/",
        "active": True,
    },
    {
        "id": "ec_digital_strategy_ai",
        "project": "ai26",
        "arena": "parliamentary",
        "actor_name": "European Commission",
        "actor_type": "government",
        "ai_formation": "unknown",
        "political_formation": "unknown",
        "source_type": "rss",
        "source_name": "European Commission Digital Strategy RSS",
        "source_url": "https://digital-strategy.ec.europa.eu/en/policies/artificial-intelligence",
        "feed_url": "https://digital-strategy.ec.europa.eu/en/rss.xml",
        "country": "EU",
        "language": "en",
        "description": "EU digital-policy source; collected into the same AI26 corpus and filtered analytically later.",
        "notes": "",
        "homepage_url": "https://digital-strategy.ec.europa.eu/",
        "active": True,

    },
    {
        "id": "india_medianama",
        "project": "ai26",
        "arena": "media",
        "actor_name": "Medianama",
        "actor_type": "media",
        "ai_formation": "unknown",
        "political_formation": "unknown",
        "source_type": "rss",
        "source_name": "Medianama RSS",
        "source_url": "https://www.medianama.com/",
        "feed_url": "https://www.medianama.com/feed/",
        "country": "IN",
        "language": "en",
        "description": "Indian digital-policy and technology reporting; Indian representation for Phase 0.",
        "notes": "Replaces the MeitY candidate feed, which serves HTML rather than RSS.",
        "homepage_url": "https://www.medianama.com/",
        "active": True,
    },
    {
        "id": "china_technode",
        "project": "ai26",
        "arena": "media",
        "actor_name": "TechNode",
        "actor_type": "media",
        "ai_formation": "unknown",
        "political_formation": "unknown",
        "source_type": "rss",
        "source_name": "TechNode RSS",
        "source_url": "https://technode.com/",
        "feed_url": "https://technode.com/feed/",
        "country": "CN",
        "language": "en",
        "description": "English-language Chinese technology reporting; competing-AI-core representation for Phase 0.",
        "notes": "Replaces the CAICT candidate feed, which returns HTTP 404.",
        "homepage_url": "https://technode.com/",
        "active": True,
    },
    {
        "id": "africa_cipit",
        "project": "ai26",
        "arena": "science",
        "actor_name": "Centre for Intellectual Property and Information Technology Law",
        "actor_type": "institute",
        "ai_formation": "unknown",
        "political_formation": "unknown",
        "source_type": "rss",
        "source_name": "CIPIT blog RSS",
        "source_url": "https://cipit.strathmore.edu/",
        "feed_url": "https://cipit.strathmore.edu/feed/",
        "country": "KE",
        "language": "en",
        "description": "African digital-policy and AI-governance research source.",
        "notes": "Validated live; activated for Phase 0 African representation.",
        "homepage_url": "https://cipit.strathmore.edu/",
        "active": True,

    },
    {
        "id": "guardian_ai",
        "project": "ai26",
        "arena": "media",
        "actor_name": "The Guardian",
        "actor_type": "media",
        "ai_formation": "unknown",
        "political_formation": "unknown",
        "source_type": "rss",
        "source_name": "The Guardian AI topic feed",
        "source_url": "https://www.theguardian.com/technology/artificialintelligenceai",
        "feed_url": "https://www.theguardian.com/technology/artificialintelligenceai/rss",
        "country": "GB",
        "language": "en",
        "description": "Mainstream media source restricted to its AI topic feed.",
        "notes": "Media articles are not equivalent to primary statements by the actors they quote.",
        "homepage_url": "https://www.theguardian.com/",
        "active": True,
    },
    {
        "id": "ainow",
        "project": "ai26",
        "arena": "elite",
        "actor_name": "AI Now Institute",
        "actor_type": "institute",
        "ai_formation": "critical_ai",
        "political_formation": "unknown",
        "source_type": "rss",
        "source_name": "AI Now Institute RSS",
        "source_url": "https://ainowinstitute.org/",
        "feed_url": "https://ainowinstitute.org/feed/",
        "country": "US",
        "language": "en",
        "description": "Seed institute for critical AI scholarship and AI accountability research.",
        "notes": "Named as a critical_ai seed in #171.",
        "homepage_url": "https://ainowinstitute.org/",
        "active": True,
    },
    {
        "id": "eu_ai_act",
        "project": "ai26",
        "arena": "parliamentary",
        "actor_name": "EU Artificial Intelligence Act",
        "actor_type": "publication",
        "ai_formation": "ai_safety",
        "political_formation": "unknown",
        "source_type": "rss",
        "source_name": "EU AI Act news RSS",
        "source_url": "https://artificialintelligenceact.eu/",
        "feed_url": "https://artificialintelligenceact.eu/feed/",
        "country": "EU",
        "language": "en",
        "description": "EU AI Act regulatory news; European institutional representation.",
        "notes": "Regulatory/governance source, not a primary EU institution feed.",
        "homepage_url": "https://artificialintelligenceact.eu/",
        "active": True,
    },
    {
        "id": "aifinland",
        "project": "ai26",
        "arena": "science",
        "actor_name": "AI Finland",
        "actor_type": "institute",
        "ai_formation": "ai_safety",
        "political_formation": "unknown",
        "source_type": "rss",
        "source_name": "AI Finland RSS",
        "source_url": "https://www.aifinland.fi/",
        "feed_url": "https://www.aifinland.fi/feed/",
        "country": "FI",
        "language": "fi",
        "description": "Finnish national AI accelerator network; semiperiphery (Finland) representation.",
        "notes": "",
        "homepage_url": "https://www.aifinland.fi/",
        "active": True,
    },
]


def active_sources():
    """Return validated-shape active RSS source configs."""
    result = []
    for source in SOURCES:
        if not source.get("active", True):
            continue
        source = dict(source)
        source.setdefault("ai_formation", "unknown")
        source.setdefault("political_formation", "unknown")
        source.setdefault("notes", "")
        if source.get("source_type") != "rss":
            raise ValueError(f"Phase 0 supports RSS only: {source['id']}")
        if source["arena"] not in ARENAS:
            raise ValueError(f"Unknown arena for {source['id']}: {source['arena']}")
        if source["actor_type"] not in ACTOR_TYPES:
            raise ValueError(f"Unknown actor_type for {source['id']}: {source['actor_type']}")
        if source["ai_formation"] not in AI_FORMATIONS:
            raise ValueError(f"Unknown ai_formation for {source['id']}: {source['ai_formation']}")
        if source["political_formation"] not in POLITICAL_FORMATIONS:
            raise ValueError(
                f"Unknown political_formation for {source['id']}: {source['political_formation']}"
            )
        result.append(source)
    return result
